AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zip

  Sample SAM Template for zip

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  LanguageTrainerUserServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.mikescherbakov.languagetraineruserservice.aws.LambdaStreamHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      SnapStart:
        ApplyOn: "PublishedVersions"
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        UserService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LanguageTrainerUserServiceFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for User Service function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  LanguageTrainerUserServiceFunction:
    Description: "UserService Lambda Function ARN"
    Value: !GetAtt LanguageTrainerUserServiceFunction.Arn
  LanguageTrainerUserServiceFunctionIamRole:
    Description: "Implicit IAM Role created for UserService function"
    Value: !GetAtt LanguageTrainerUserServiceFunctionRole.Arn
